config/routes.rb
  get    '/all/textos/Visible'          =>               'posts#textos',                               :as => :model_textos
  get    '/all/links/Visible'           =>               'posts#links',                                :as => :model_links
  get    '/all/images/Visible'          =>               'posts#images',                               :as => :model_images
  get    '/all/videos/mobileVisible'    =>               'posts#videos',                               :as => :model_videos
  delete '/posts/destroy/:post_id'      =>               'posts#destroy',                              :as => :post_destroy
 
#SEARCHS
  get  '/directory/video/:letter'       =>               'searchs#letter_videos',                      :as => :directory_video
  get  '/directory/image/:letter'       =>               'searchs#letter_images',                      :as => :directory_image
  get  '/directory/link/:letter'        =>               'searchs#letter_links',                       :as => :directory_link
  get  '/directory/texto/:letter'       =>               'searchs#letter_textos',                      :as => :directory_texto
  get  '/blog/textos'                   =>               'searchs#textos',                             :as => :adv_model_textos
  get  '/blog/links'                    =>               'searchs#links',                              :as => :adv_model_links
  get  '/blog/images'                   =>               'searchs#images',                             :as => :adv_model_images
  get  '/blog/videos'                   =>               'searchs#videos',                             :as => :adv_model_videos
  get  '/tag_cloud'                     =>               'searchs#tag_cloud',                          :as => :tag_cloud
  get  '/posts/results/date/:date'      =>               'searchs#post_date',                          :as => :post_date

  post  '/search/posts'                 =>               'searchs#research',                           :as => :search
  post  '/search/posts/texts'           =>               'searchs#research_text',                      :as => :search_text
  post  '/search/posts/links'           =>               'searchs#research_link',                      :as => :search_link
  post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  post  '/search/posts/videos'          =>               'searchs#research_video',                     :as => :search_video
  #post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  get   '/directory/posts'              =>               'searchs#index',                              :as => :directory_posts_all

  get  '/directory/posts/:letter'       =>               'searchs#letter',                             :as => :directory_posts_letter
  get  '/posts/tagged/:search'          =>               'searchs#search',                             :as => :posts_tagged_with

#  map.resources :links
#  map.resources :videos
#  map.resources :textos  
  
 # map.resources :users, :collection => {:prioritize_tasks => :post}

#CONTENT
  get    '/content/edit/:id'            =>               'contents#edit',                             :as => :edit_content
  patch  '/content/update/:id'          =>               'contents#update',                           :as => :update_content

#DASHBOARD
  get    '/dashboard'                   =>               'dashboard#show',                            :as => :dashboard
  #post   '/photo/get_new'               =>               'dashboard#get_new_photo',                   :as => :get_new_photo
  get    '/photo/new'                   =>               'dashboard#new_photo',                       :as => :new_photo
  post   '/photo/create'                =>               'dashboard#create_photo',                    :as => :create_photo
  delete '/photo/destroy'               =>               'dashboard#destroy_photo',                   :as => :destroy_photo
  get    '/demo/new'                    =>               'dashboard#new_demo',                        :as => :new_demo
  patch  '/demo/create'                 =>               'dashboard#create_demo',                     :as => :create_demo
  delete '/demo/destroy'                =>               'dashboard#destroy_demo',                    :as => :destroy_demo
  get    '/paragraphe/edit'             =>               'dashboard#paragraphe',                      :as => :paragraphe

#MOVIES
  get    '/movies/:id/edit'             =>               'movies#edit',                                :as => :edit_movie
  get    '/positions/movies'            =>               'movies#position',                            :as => :position_movie
  get    '/movies/:id/picture/new'      =>               'movies#new_picture',                         :as => :new_movie_picture
  post   '/movies/:id/picture/create'   =>               'movies#create_picture',                      :as => :picture
  delete '/movies/:id/picture/destroy'  =>               'movies#destroy_picture',                     :as => :remove_picture
  delete '/movies/:id/destroy'          =>               'movies#destroy',                             :as => :destroy_movie
  get    '/movies/:id/:style.:format'   =>               'movies#connect',                             :as => :connect
  get    '/services'                    =>               'movies#index',                               :as => :services
  get    '/fr/ervices'                  =>               'movies#index',                               :as => :servicesfr

#FOLIOS
  get    '/games'                       =>               'folios#index',                               :as => :folios
  get    '/fr/jeux'                     =>               'folios#index',                               :as => :frfolios
  get    'games/new'                    =>               'folios#new',                                 :as => :new_folio         
  get    '/games/:id/edit'              =>               'folios#edit',                                :as => :edit_folio
  get    '/positions/games'             =>               'folios#position',                            :as => :position_folio
  get    '/games/:id/picture/new'       =>               'folios#new_picture',                         :as => :new_position_folio
  post   '/games/create'                =>               'folios#create',                              :as => :create_folio
  post   '/games/picture/create'        =>               'folios#create_picture',                      :as => :create_folio_picture
  post   '/folios/prioritize_tasks'     =>               'folios#prioritize_tasks',                    :as => :folio_prioritize_tasks
  delete '/games/:id/picture/destroy'   =>               'folios#destroy_picture',                     :as => :remove_folio_picture
  delete '/games/destroy/:id'           =>               'folios#destroy',                             :as => :destroy_folio

 #keep below because of the destroy priority!
  resources :movies, :collection => {:prioritize_tasks => :post}
  resources :folios, :collection => {:prioritize_tasks => :post}
  resources :search, :collection => {:search => :get}
  
  resources :users

# map.connect '/movies/:id/:style.:format', :controller => :movies, :action => :download
#USERS
  get    '/user/:id'                    =>               'users#show',                                     :as => :show_user
  get    '/positions/users'             =>               'users#position',                                 :as => :position
  get    '/aboutus'                     =>               'users#index',                                    :as => :aboutus
  get    '/fr/apropos'                  =>               'users#index',                                    :as => :aboutusfr
  get    '/signup'                      =>               'users#new',                                      :as => :signup
  get    '/fr/users/:id'                =>               'users#parafr',                                   :as => :parafr
  get    '/account/edit'                =>               'users#edit',                                     :as => :user_edit
  patch  '/account/update/:id'          =>               'users#update',                                   :as => :user_update
  post   '/users/create'                =>               'users#create',                                   :as => :user_create
#USER_SESSIONS
  get    '/login'                       =>               'user_sessions#new'#,                              :as => :login  
  
#SUPPORT
  get    '/fr/notifier/mailform'        =>               'supports#mailform',                              :as => :mailformfr
  get    '/notifier/mailform'           =>               'supports#mailform',                              :as => :mailform
  get    '/contactus'                   =>               'supports#show',                                  :as => :notifier
  get    '/fr/contact'                  =>               'supports#show',                                  :as => :notifierfr
  get    '/notifier/my_mailer'          =>               'supports#my_mailer',                             :as => :my_mailer
  post   '/send_mail'                   =>               'supports#send_mail',                             :as => :send_mail

#CALENDAR
  get   '/calendars/:id/:year/:month'   =>               'calendar#calendar',                              :as => :post_calendars 
  

#  map.with_options(:controller => :pages, :action => :show) do |page|    
 #   page.news '/news', :page => 'news'
  #  page.contactus '/contactus', :page => 'contactus'        
  #end
  
#FRENCH
  get    '/fr/mobile'                   =>               'french#show',        :page => 'mobile',          :as => :mobile_fr

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  #before_action :require_user
  before_action :get_user, except: [:destroy_photo, :destroy_demo]
  before_action :get_movie, only: [:show]
  protect_from_forgery only: [:create_photo]
  
  def show    
    @tags = User.tag_counts_on(:tags)
    #@user = current_user
    @post = Post.new
    if @user
      @posts = @user.posts.all.paginate(:page => params[:page], :per_page => 5)      
    else
      redirect_to root_url
    end
  end

  def new_photo
    #@user = current_user
    render :layout => false
  end

  def paragraphe
    #@user = current_user
    #render :layout => false
  end

  def create_photo
    #User.update(@user.id, user_photo_params)
    respond_to do |format|
      if current_user.update(user_photo_params)
        #photo_file_name: params[:user][:photo].original_filename)
        # puts @user.photo_file_name.nil?
        #photo_file_name: params[:user][:photo].original_filename, photo_content_type: params[:user][:photo].content_type)#, photo_file_size: params[:user][:photo].original_file_name#user_avatar_params)
        #puts is good too
        #Rails.logger.debug("my content_type :  #{user_photo_params}")
        #Rails.logger.debug("my object :  #{params[:user][:photo].content_type}")
        #add_column :users, :photo_file_name, :string
        #add_column :users, :photo_content_type, :string
        #add_column :users, :photo_file_size, :integer
        #add_column :users, :photo_updated_at, :datetime
        #if @user.update(user_avatar_params)
        #photo_file_name: params[:user][:original_filename], photo_content_type: params[:user][:content_type])
        flash[:notice] = "Your picture was successfully created"
        format.json {render :json => {response: 'success', data: "parent.location.href = \"#{dashboard_path}\";" }}
        #redirect_to dashboard_url
      else
        flash[:notice] = "We accept JPG - JPEG - PNG - BMP format only!"
        #format.js {render js: "parent.location.href = \"#{dashboard_path}\";"}
        format.json {render :json => {response: 'error', data: "parent.location.href = \"#{dashboard_path}\";" }}
        #redirect_to dashboard_url
      end
    end
  end 
  
  def new_demo
    #@user = current_user

    render :layout => false
  end

  def create_demo
    #@user = current_user
    if @user.update(user_demo_params)#.update_attributes(params[:user])
     flash[:notice] = "Your movie was successfully created"
     redirect_to dashboard_url
     else
     flash[:notice] = "We allow FLV format only!"
       redirect_to dashboard_url
     end
  end 
  
  def edit
    #@user = current_user
  end

  def destroy_photo    
    @user = current_user.photo.destroy

    current_user.update_attribute(:photo_file_name, nil)
    current_user.update_attribute(:photo_content_type, nil)
    current_user.update_attribute(:photo_file_size, "")
    current_user.update_attribute(:photo_updated_at, "")
    flash[:notice] = "Your picture was successfully deleted"
    redirect_to dashboard_url  
  end
  
  def destroy_demo    
    @user = current_user.demo.destroy

    current_user.update_attribute(:demo_file_name, nil)
    current_user.update_attribute(:demo_content_type, nil)
    current_user.update_attribute(:demo_file_size, "")
    current_user.update_attribute(:demo_updated_at, "")
    flash[:notice] = "Your movie was successfully deleted"
    redirect_back_or_to dashboard_url  
  end
  
private
  def get_user
     @user = current_user
  end
  def get_movie
     @movie = Movie.all
  end
  def user_photo_params
    #params.require(:user).permit(:photo)
    params.require(:user).permit(:photo)
  end
  
  def user_demo_params
    params.require(:user).permit(:demo)
  end
end

app/views/dashboard/_post.html.erb
<% @user.posts.each do |post| %>
<div class="post_full"> 
   <% if post.url.blank? || post.url == 'http://'%><% else %>
   <h3><%= link_to  post.url,  post.url, :popup => 'true' %></h3>
   <% end %>
   <h3><%= "<span>#{post.title}</span>" unless post.title.blank? %></h3>
   <%= auto_link(simple_format(post.body), :href_options => { :target => "_new"},:rel => "nofollow") %>
<div class="clear">&nbsp;</div>   
  <div class="inner_bottom"></div>
  <div class="user_box_bg">
    <div class="user_icon">
      <% if current_page?(dashboard_url) %>
        <%= link_to (image_tag 'comdel.png', :mouseover => 'comdel1.png'), "/posts/#{post.id}" %>
      <% else %>
      <% end %>
      <div class="icn_<%= post.model %>"></div>
      <div class="blog_icon"><span>posted&nbsp;</span><span style="font-weight:bold;"><%= time_ago_in_words(post.created_at) %></span><span>&nbsp;ago</span></div>
    </div> 
  </div>
</div>
<div class="clear">&nbsp;</div>
<% end %>

app/views/dashboard/new_demo.html.haml
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
= csrf_meta_tag
= javascript_include_tag 'application'
= stylesheet_link_tag 'application'

:css
  /*body {background: #EEE;}
  h3 {text-align:center;font-weight:bold;font-size:18px;}
  .form_wrapper{width:200px;margin:0 auto;}
  label {font-size:12px;}
  input[type="text"] {width:200px;}
  input[type="password"] {width:200px;}*/
  
  body {background: #CCC /*url(/assets/bg_main.png) top left repeat;*/}
  h2 {text-align:center;}
  .notifier {padding-left:80px; width:340px;float:left;}
  input[type="text"] {width:300px;}
  .column_left {float:left; width:100px;}
  .column_left input[type="checkbox"] {float:right;padding-right:20px;}
  .column_right {float:right; width:100px;}
  .column_right input[type="checkbox"] {float:right;}
  #errorExplanation {margin-left:-50px !important;}
  form {padding:20px;background:#EEE;width:300px;box-shadow:-3px 8px 10px 2px #999;-moz-box-shadow:-3px 8px 10px 2px #999;-webkit-box-shadow:-5px 10px 10px #999;}
.clear &nbsp;
%h2 New Demo
.clear &nbsp;  

.notifier
  = form_for current_user, :url => create_demo_url, :html => { :multipart => true }, :remote => true do |f|

    %h3
      Choose a movie for your Profile, LESS then 30 megabites!
  
    .clear &nbsp;
    %fieldset
      = f.file_field :demo
    .clear &nbsp; 
    = f.submit 'Add'

app/views/dashboard/new_photo.html.haml
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
= csrf_meta_tag
= javascript_include_tag 'application'
= stylesheet_link_tag 'application'

:css
  /*body {background: #EEE;}
  h3 {text-align:center;font-weight:bold;font-size:18px;}
  .form_wrapper{width:200px;margin:0 auto;}
  label {font-size:12px;}
  input[type="text"] {width:200px;}
  input[type="password"] {width:200px;}*/
  
  body {background: #CCC /*url(/assets/bg_main.png) top left repeat;*/}
  h2 {text-align:center;}
  .notifier {padding-left:80px; width:340px;float:left;}
  input[type="text"] {width:300px;}
  .column_left {float:left; width:100px;}
  .column_left input[type="checkbox"] {float:right;padding-right:20px;}
  .column_right {float:right; width:100px;}
  .column_right input[type="checkbox"] {float:right;}
  #errorExplanation {margin-left:-50px !important;}
  form {padding:20px;background:#EEE;width:300px;box-shadow:-3px 8px 10px 2px #999;-moz-box-shadow:-3px 8px 10px 2px #999;-webkit-box-shadow:-5px 10px 10px #999;}
.clear &nbsp;
%h2 New Picture
.clear &nbsp;

.notifier
  = form_for current_user, :url => create_photo_url, :method => :post, :remote => true, authenticity_token: true do |f|
    = f.error_messages

    %h3 Choose at least a square Picture, NEAR 200 X 200
    .clear &nbsp;
    %fieldset
      = f.file_field :photo, id: 'photo_file', name: "uploadFile"
    .clear &nbsp;
    = f.submit 'Add'

:javascript
  const form = document.getElementById("edit_user_#{current_user.id}");

  form.addEventListener("submit", submitForm);

  function submitForm(e) {
    e.preventDefault();
    //const name = document.getElementById("name");
    let files = e.target.uploadFile.files[0]
    let csrf = e.target.authenticity_token.value;
    //const files = document.getElementById("photo_file").value;//.src;
    //console.log(files)
    const form_data = new FormData();
    const path = window.location.pathname;
	
    var id = path.split('/');
    id = id[1];
	
    if (files == window.location.href){
    alert('Please select a file and crop it first')
    return
    } else {
      let user_data = {user: {photo: files}}
	  
      form_data.append("name", "avatar");
      for (let dataKey in user_data) {
        if(dataKey === 'user') {
        //  append nested object
          for (let photoKey in user_data[dataKey]) {
            form_data.append(`user[${photoKey}]`, user_data[dataKey][photoKey]);
          }
        }
        //else {
        //form_data.append(dataKey, user[dataKey]);
        //}
      }
      //form_data.append("photo", files)
      form_data.append("authenticity_token", csrf)
	
      fetch("#{ AppConfig.url.root }/photo/create" , {
        method: 'POST',
        dataType: 'script',
        body: form_data,
        headers: { "X-CSRFToken": getCookie("csrftoken") },
        //headers: {
        //  "Content-Type": "multipart/form-data"
        //}
      }).then(res => res.json()).then(res => {
        //var message = document.getElementById('message')
        console.log('res: ', res)
        if(res.response == "success"){
          eval(res.data);
        } else {
          var cont = document.getElementById('container')
          cont.innerHTML = "<div id='flash_error'>" + res.data + "</div>"
          //message.innerHTML = "<span class='error_mess'>Try to upload an avatar again</span>";
        }
        console.log('res: ', res)
      }).catch((err) => ("Error occured", err));
    }	
  }
	

app/views/dashboard/paragraphe.html.erb
    <h2>Add content</h2>
    <p class="tagline">Add or modify the information about your account</p>
<div class="clear">&nbsp;</div>
  <%= form_for @user, :url => user_update_path(@user.id) do |f| %>
    <%= f.error_messages %>
<h3 style="color:green;">Francais</h3>
     <fieldset>
    <%= f.label :par1, 'paragraphe 1 (500 caracteres max)' %><br/>
    <%= f.text_area :par1, :class => 'tinymce' %>
     </fieldset>


     <fieldset>
    <%= f.label :par2, 'paragraphe 2 (500 caracteres max)' %><br/>
    <%= f.text_area :par2, :class => 'tinymce' %>
     </fieldset>

<h3 style="color:green;">English</h3>
    <fieldset>
    <%= f.label :par3, 'column 1 (500 characters max)' %><br/>
    <%= f.text_area :par3, :class => 'tinymce' %>
     </fieldset>


     <fieldset>
    <%= f.label :par4, 'column 2 (500 characters max)' %><br/>
    <%= f.text_area :par4, :class => 'tinymce' %>
     </fieldset>

<div class="clear">&nbsp;</div>
<%= f.submit 'Update' %>

<% end %>

<% content_for :js do %>
  <%#= javascript_include_tag '/javascripts/tinymce/jscripts/tiny_mce/jquery.tinymce.js' %>  
<% javascript_tag do %>

	$().ready(function() {

		$('textarea.tinymce').tinymce({

			// Location of TinyMCE script

			script_url : '/assets/tinymce/jscripts/tiny_mce/tiny_mce.js',



			// General options

			mode : "exact",
			elements : "elm1",
			theme : "advanced",
			skin : "o2k7",
			skin_variant : "black",

			plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",



			// Theme options

			theme_advanced_buttons1 : "save,newdocument,|,styleselect,|,formatselect,|,fontselect,|,fontsizeselect",

			theme_advanced_buttons2 : "justifyleft,justifycenter,justifyright,justifyfull,|,bold,italic,underline,strikethrough,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,fullscreen",

			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,ltr,rtl",

			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,|,charmap,emotions,iespell,media,advhr",
			theme_advanced_buttons5 : "cut,copy,paste,pastetext,pasteword,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,print,|,link,unlink,anchor,image,cleanup,help,code",

			theme_advanced_toolbar_location : "top",

			theme_advanced_toolbar_align : "center",

			theme_advanced_statusbar_location : "bottom",

			theme_advanced_resizing : true,


			// Example content CSS (should be your site CSS)

			//content_css : "css/content.css",



			// Drop lists for link/image/media/template dialogs

			template_external_list_url : "lists/template_list.js",

			external_link_list_url : "lists/link_list.js",

			external_image_list_url : "lists/image_list.js",

			media_external_list_url : "lists/media_list.js",



			// Replace values for the template plugin

			template_replace_values : {

				username : "<%= current_user.login %>",

				staffid : "<%= current_user.id %>"

			}

		});

	   jQuery('<input>').attr('type', 'hidden').attr('name','authenticity_token').val('<%= form_authenticity_token %>').prependTo('#submit_block');
     jQuery('form#new_post').attr('method', 'POST');
     jQuery('<input>').attr('type', 'submit').attr('name','commit').val('Submit Post').attr('id', "post_submit").appendTo('#submit_block');
});
<% end %>
<% end %>
<script type="text/javascript">
if (document.location.protocol == 'file:') {
	alert("The examples might not work properly on the local file system due to security settings in your browser. Please use a real webserver.");
}
</script>

app/views/dashboard/show.html.erb
<% content_for :head do %>
<style>
  body {background: #222;}
  #footer {background: #999;}
</style>
<% end %>

<% content_for :hd_inner do %>

<div class="photo">
  <%= link_to(image_tag(current_user.photo.url, :size => '200x200'), new_photo_url(@user.id), :title => current_user.login) %>
</div>

<div class="user_info">
<h2><%= @user.login %> </h2>
<% unless @user.tag_type.blank? %>
<h3 style="font-size:22px;"><%= @user.tag_type.humanize %></h3>
<% end %>
<h3 style="font-size:22px;"><%= @user.location %> </h3>
<!--<h3><%= @user.phone %> </h3>
<h3><%= @user.email %> </h3>
<h3><%= @user.dob %> </h3>-->
</div>

<% end %>

<% if current_user.photo_file_name.blank? %>

  <span class="upload picture">
    <%#= facebox_link_to("#{image_tag 'add.gif', :size => '18x18', :title => '200X200'} Add Picture", :url => new_photo_url) %>
    <%= link_to(raw("#{image_tag 'add.gif', :size => '18x18', :title => '200X200'} Add Picture"), new_photo_url, :rel => "shadowbox;width=500;height=300;") %>
  </span>
<% else %>

<%= button_to "Destroy picture", { :controller=>'dashboard', :action=>'destroy_photo' }, :method => :delete, :confirm => "Are you sure?" %>
<% end %>
<% if current_user.demo_file_name.blank? %>

<span class="upload" style="position:absolute;left:10px;top:50px;"><%#= facebox_link_to("#{image_tag 'add.gif', :size => '18x18', :title => '30mb/max'} Add Movie", :url => new_demo_url) %>
    <%= link_to(raw("#{image_tag 'add.gif', :size => '18x18', :title => '30mb/max'} Add Movie"), new_demo_url, :rel => "shadowbox;width=500;height=400;") %>  
  </span>

<% else %>

<span style="position:absolute;left:10px;top:50px;"><%= button_to "Destroy movie", { :controller=>'dashboard', :action=>'destroy_demo' }, method: :delete, :confirm => "Are you sure?" %></span>
<% end %>
<span class="upload" style="position:absolute;left:10px;top:80px;">
	<%= link_to(raw("#{image_tag 'add.gif', :size => '18x18', :title => '30mb/max'} Add games"), new_folio_url) %>
</span>
<span class="upload" style="position:absolute;left:10px;top:110px;">
<%= link_to(raw("#{image_tag 'add.gif', :size => '18x18', :title => '30mb/max'} Edit games"), position_folio_url) %>
</span>
  
     <div id="blog_wrapper">
       <div class="pusher" id="slideToggle">
       
         <div id="blog2" name="blog"><%= link_to "[-] Hide create post", "javascript:blogger('blog1');",:id => "myHeader1" %>
         </div> 
       
         <div id="blog1" name="blog" style="display:none;"><%= link_to "[+] Show create post", "javascript:blogger('blog2');",:id => "myHeader2" %>
         </div>
         <div class="clear">&nbsp;</div>
       </div>
       
          <%= render 'shared/quick_post', :object => @post %>
        
       <div class="posts">
         <%= render @posts %>
         <div class="paginate"><%= will_paginate @posts %></div>
       </div>
       </div>
      
<% content_for :js do %>
<%= javascript_include_tag 'blog' %>
  <%#= javascript_include_tag 'tinymce/jscripts/tiny_mce/jquery.tinymce.js' %>  

<% end %>
<% content_for :js do %>
<% javascript_tag do %>

	$().ready(function() {

		$('textarea.tinymce').tinymce({

			// Location of TinyMCE script

			script_url : '/assets/tinymce/jscripts/tiny_mce/tiny_mce.js',



			// General options

			mode : "exact",
			elements : "elm1",
			theme : "advanced",
			skin : "o2k7",
			skin_variant : "black",

			plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",



			// Theme options

			theme_advanced_buttons1 : "save,newdocument,|,styleselect,|,formatselect,|,fontselect,|,fontsizeselect",

			theme_advanced_buttons2 : "justifyleft,justifycenter,justifyright,justifyfull,|,bold,italic,underline,strikethrough,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,fullscreen",

			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,ltr,rtl",

			theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,|,charmap,emotions,iespell,media,advhr",
			theme_advanced_buttons5 : "cut,copy,paste,pastetext,pasteword,|,insertdate,inserttime,preview,|,forecolor,backcolor,|,print,|,link,unlink,anchor,image,cleanup,help,code",

			theme_advanced_toolbar_location : "top",

			theme_advanced_toolbar_align : "center",

			theme_advanced_statusbar_location : "bottom",

			theme_advanced_resizing : true,


			// Example content CSS (should be your site CSS)

			//content_css : "css/content.css",



			// Drop lists for link/image/media/template dialogs

			template_external_list_url : "lists/template_list.js",

			external_link_list_url : "lists/link_list.js",

			external_image_list_url : "lists/image_list.js",

			media_external_list_url : "lists/media_list.js",



			// Replace values for the template plugin

			template_replace_values : {

				username : "<%= current_user.login %>",

				staffid : "<%= current_user.id %>"

			}

		});

	   jQuery('<input>').attr('type', 'hidden').attr('name','authenticity_token').val('<%= form_authenticity_token %>').prependTo('#submit_block');
     jQuery('form#new_post').attr('method', 'POST');
     jQuery('<input>').attr('type', 'submit').attr('name','commit').val('Submit Post').attr('id', "post_submit").appendTo('#submit_block');
});


jQuery(document).ready(function (){
jQuery('.post_full iframe').each(function(){
var url = jQuery(this).attr("src")
jQuery(this).attr("src",url+"?wmode=transparent")
});
});
<% end %>
<% end %>