config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #root "posts#index"
    #root "posts#index"
    
#Ankh::Application.routes.draw do

  get    '/login'                       =>               'user_sessions#new',                         :as => :login
  post   '/create_session'              =>               'user_sessions#create',                      :as => :create_session
  delete '/destroy_session'             =>               'user_sessions#destroy',                     :as => :destroy_session
  
  
#  map.resources :users, :collection => {:prioritize_tasks => :post}
   resources :posts 

#POSTS
  get    '/post/:id'                    =>               'posts#show',                                 :as => :show_post
  post   '/create/post'                 =>               'posts#create',                               :as => :create_post
  get    '/blogger'                     =>               'posts#blogger',                              :as => :blog
  get    '/posts/:id/blogpost'          =>               'posts#edit',                                 :as => :edit_blog
  patch  '/posts/:id/blogupd'           =>               'posts#update',                               :as => :update_blog
  get    '/posts/all/Visible'           =>               'posts#state',                                :as => :visible
  get    '/posts/all/Restricted'        =>               'posts#restricted',                           :as => :restricted
  get    '/fr/posts/all/Visible'        =>               'posts#visiblefr',                            :as => :visiblefr
  get    '/all/textos/Visible'          =>               'posts#textos',                               :as => :model_textos
  get    '/all/links/Visible'           =>               'posts#links',                                :as => :model_links
  get    '/all/images/Visible'          =>               'posts#images',                               :as => :model_images
  get    '/all/videos/mobileVisible'    =>               'posts#videos',                               :as => :model_videos
  delete '/posts/destroy/:post_id'      =>               'posts#destroy',                              :as => :post_destroy
 
#SEARCHS
  get  '/directory/video/:letter'       =>               'searchs#letter_videos',                      :as => :directory_video
  get  '/directory/image/:letter'       =>               'searchs#letter_images',                      :as => :directory_image
  get  '/directory/link/:letter'        =>               'searchs#letter_links',                       :as => :directory_link
  get  '/directory/texto/:letter'       =>               'searchs#letter_textos',                      :as => :directory_texto
  get  '/blog/textos'                   =>               'searchs#textos',                             :as => :adv_model_textos
  get  '/blog/links'                    =>               'searchs#links',                              :as => :adv_model_links
  get  '/blog/images'                   =>               'searchs#images',                             :as => :adv_model_images
  get  '/blog/videos'                   =>               'searchs#videos',                             :as => :adv_model_videos
  get  '/tag_cloud'                     =>               'searchs#tag_cloud',                          :as => :tag_cloud
  get  '/posts/results/date/:date'      =>               'searchs#post_date',                          :as => :post_date

  post  '/search/posts'                 =>               'searchs#research',                           :as => :search
  post  '/search/posts/texts'           =>               'searchs#research_text',                      :as => :search_text
  post  '/search/posts/links'           =>               'searchs#research_link',                      :as => :search_link
  post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  post  '/search/posts/videos'          =>               'searchs#research_video',                     :as => :search_video
  #post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  get   '/directory/posts'              =>               'searchs#index',                              :as => :directory_posts_all

  get  '/directory/posts/:letter'       =>               'searchs#letter',                             :as => :directory_posts_letter
  get  '/posts/tagged/:search'          =>               'searchs#search',                             :as => :posts_tagged_with

#  map.resources :links
#  map.resources :videos
#  map.resources :textos  
  
 # map.resources :users, :collection => {:prioritize_tasks => :post}

#CONTENT
  get    '/content/edit/:id'            =>               'contents#edit',                             :as => :edit_content
  patch  '/content/update/:id'          =>               'contents#update',                           :as => :update_content

#DASHBOARD
  get    '/dashboard'                   =>               'dashboard#show',                            :as => :dashboard
  #post   '/photo/get_new'               =>               'dashboard#get_new_photo',                   :as => :get_new_photo
  get    '/photo/new'                   =>               'dashboard#new_photo',                       :as => :new_photo
  post   '/photo/create'                =>               'dashboard#create_photo',                    :as => :create_photo
  delete '/photo/destroy'               =>               'dashboard#destroy_photo',                   :as => :destroy_photo
  get    '/demo/new'                    =>               'dashboard#new_demo',                        :as => :new_demo
  patch  '/demo/create'                 =>               'dashboard#create_demo',                     :as => :create_demo
  delete '/demo/destroy'                =>               'dashboard#destroy_demo',                    :as => :destroy_demo
  get    '/paragraphe/edit'             =>               'dashboard#paragraphe',                      :as => :paragraphe

#MOVIES
  get    '/movies/:id/edit'             =>               'movies#edit',                                :as => :edit_movie
  get    '/positions/movies'            =>               'movies#position',                            :as => :position_movie
  get    '/movies/:id/picture/new'      =>               'movies#new_picture',                         :as => :new_movie_picture
  post   '/movies/:id/picture/create'   =>               'movies#create_picture',                      :as => :picture
  delete '/movies/:id/picture/destroy'  =>               'movies#destroy_picture',                     :as => :remove_picture
  delete '/movies/:id/destroy'          =>               'movies#destroy',                             :as => :destroy_movie
  get    '/movies/:id/:style.:format'   =>               'movies#connect',                             :as => :connect
  get    '/services'                    =>               'movies#index',                               :as => :services
  get    '/fr/ervices'                  =>               'movies#index',                               :as => :servicesfr

#FOLIOS
  get    '/games'                       =>               'folios#index',                               :as => :folios
  get    '/fr/jeux'                     =>               'folios#index',                               :as => :frfolios
  get    'games/new'                    =>               'folios#new',                                 :as => :new_folio         
  get    '/games/:id/edit'              =>               'folios#edit',                                :as => :edit_folio
  get    '/positions/games'             =>               'folios#position',                            :as => :position_folio
  get    '/games/:id/picture/new'       =>               'folios#new_picture',                         :as => :new_position_folio
  post   '/games/create'                =>               'folios#create',                              :as => :create_folio
  post   '/games/picture/create'        =>               'folios#create_picture',                      :as => :create_folio_picture
  post   '/folios/prioritize_tasks'     =>               'folios#prioritize_tasks',                    :as => :folio_prioritize_tasks
  delete '/games/:id/picture/destroy'   =>               'folios#destroy_picture',                     :as => :remove_folio_picture
  delete '/games/destroy/:id'           =>               'folios#destroy',                             :as => :destroy_folio

 #keep below because of the destroy priority!
  resources :movies, :collection => {:prioritize_tasks => :post}
  resources :folios, :collection => {:prioritize_tasks => :post}
  resources :search, :collection => {:search => :get}
  
  resources :users

# map.connect '/movies/:id/:style.:format', :controller => :movies, :action => :download
#USERS
  get    '/user/:id'                    =>               'users#show',                                     :as => :show_user
  get    '/positions/users'             =>               'users#position',                                 :as => :position
  get    '/aboutus'                     =>               'users#index',                                    :as => :aboutus
  get    '/fr/apropos'                  =>               'users#index',                                    :as => :aboutusfr
  get    '/signup'                      =>               'users#new',                                      :as => :signup

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_user, :except => [:index,:show]
  before_action :get_movie, :only => [:destroy,:destroy_picture]
  
  def index
    @movie = Movie.find(:all).paginate(:page => params[:page], :per_page => 14)
    respond_to do |format|
      format.html   #renders index.html.erb
      format.iphone #renders index.iphone.erb
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @movies = Movie.find(:all)
    respond_to do |format|
      format.html
      format.iphone { render :layout => 'admin' }
    end
  end

  def position
    @user = User.all
    @movie = Movie.all
    respond_to do |format|
      format.html   # renders index.html.erb
      format.iphone# renders index.iphone.erb
    end
  end
  
  def new
    @movie = Movie.new
    render :layout => false
  end
  
  def update
     @movie = Movie.find(params[:id])

    if @movie.update_attributes(params[:movie])      
      flash[:notice] = "Movie was successfully updated."
      redirect_to "/movies/#{@movie.id}"
    else
     flash[:notice] = "You made a mistake.*CARFEFUL* (max lenght & required field)" 
     redirect_to :back
    end
  end
  
  def create
    @movie = current_user.movies.build(params[:movie])
    
     if @movie.save
       redirect_to "/movies/#{@movie.id}"
       flash[:notice] = "Movie successfully created"
     else
       redirect_to dashboard_url
       flash[:notice] = "We accept FLV format of 70mb or less"
     end    
  end
  
  def destroy   
    @movie = @movie.destroy(params[:movie_id])
    flash[:notice] = "Movie successfully deleted"
    redirect_to "/dashboard"
  end
  
  def new_picture
    @movie = Movie.find(params[:id])
    render :layout => false
  end

  def edit
    @movie = Movie.find(params[:id])
    render :layout => false
  end

  def create_picture
    @movie = Movie.find(params[:id])

     if @movie.update_attributes(params[:movie])
     flash[:notice] = "Your picture was successfully created"
       redirect_to :back
     else
       render_to_facebox :back
     end
  end 
  
  def destroy_picture 
    @movies = @movie.picture.destroy

    @movie.update_attribute(:picture_file_name, nil)
    @movie.update_attribute(:picture_content_type, nil)
    @movie.update_attribute(:picture_file_size, "")
    @movie.update_attribute(:picture_updated_at, "")
    flash[:notice] = "Your picture was successfully deleted"
    redirect_to :back   
  end
  
  def download
    require 'mime/types'
    head(:not_found) and return if (movie = Movie.find(params[:id])).nil?
    #head(:forbidden) and return unless track.downloadable?

    path = movie.flv.path
    #head(:bad_request) and return unless File.exist?(path) #&& params[:format].to_s == File.extname(path).gsub(/^\.+/,'')

    send_file_options = {:type => MIME::Types.type_for(path)}
    #send_file_options = {:type => File.mime_type?(path)}
    
    #case SETTINGS['send_file_method']
    #when :apache then send_file_options[:x_sendfile] = true
    #when :nginx then head(:x_accel_redirect => path.gsub(Rails.root,''), :content_type => send_file_options[:type]) and return
    #end

    send_file(path,send_file_options)
  end

  def prioritize_tasks
   movies = Movie.find(:all)
     movies.each do |movie|
       movie.position = params[:movie].index(movie.id.to_s) + 1
       movie.save
     end 
    render :nothing => true
  end 
  
private
    def get_movie
      @movie = Movie.find_by_id(params[:id])
    end
  
end

app/views/movies/_movie.html.erb
<% if current_page?('/positions/movies') %>
<li id="movie_<%= movie.id %>" style="width:500px;position:relative;padding-top:7px;padding-bottom:7px;border-top:1px dotted #bbb;"><%= link_to image_tag(movie.picture.url, :size => '75x75'), movie_url(movie.id), :title => movie.name %>
<span style="position:absolute;height:25px;width:300px;top:19px;left:130px;"><%= truncate(movie.name,20,"...") %></span>
<span style="font-size:25px;"><%= movie.position %></span>
<span style=" cursor: move;float:right;" class="handle"><%= image_tag 'sortable.gif', :style => 'padding:5px 0 0 5px;' %></span>
</li>
<% else %>
<% if current_page? movie_url(@movie.id) %>
<div class="items">
<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (1) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (2) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (3) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (4) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (5) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (6) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>
</div>

<div class="items">
<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (7) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (8) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (9) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (10) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (11) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (12) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>
</div>

<% else %>
<li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
<% end %>
<% end %>

app/views/movies/new.html.erb
<%= form_for @movie, :html => { :multipart => true } do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  
   <div>
  <%= f.label :description, 'Description' %><br/>
  <span>Between 1 to 500 caracters!!!</span><br/>
   <%= f.text_area :description, :cols => 10, :rows => 5 %>
  </div> 
   
  <fieldset>
    <%= f.file_field :flv %>
  </fieldset>
  <%= f.submit 'Add' %>
<% end %>

app/views/movies/show.html.erb
<% content_for :head do %>
  <style type="text/css">
          #header{height:510px !important;} 
          #header_inner{height:420px !important;width:780px;} 
  </style>
<% end %>
<% content_for :hd_inner do %>
 <div class="clear">&nbsp;</div> 
<div id="player_wrap">

	<!-- player container and a nested <h3 style="width:780px;text-align:center;">play button as PNG image -->
	<a id="player" href="">
	 You need to have <%= link_to 'Flash Player','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash' %> installed to display this video.
	</a>
</div>

<h3 style="width:780px;font:size:14px;text-align:center;padding-bottom:10px;"><%= simple_format h(@movie.name)%></h3>
<% end %>


<div id="clips" class="scrollable">
  <div class="items">
<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (1) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (2) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (3) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (4) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (5) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (6) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>

<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (7) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (8) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (9) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (10) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (11) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (12) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>

<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (13) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (14) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (15) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (16) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (17) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (18) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>

</div>
</div>

<a class="next browse right"></a>
<a class="prev browse left"></a>


<h4 style="width:780px;padding-top:10px;font-size:14px !important;text-align:center;">Description</h4>
<div style="width:510px;margin:0 auto;padding:10px;">
            <span><%= simple_format h(@movie.description)%></span>
</div>


<% content_for :footer do %>
  <% if current_user.nil? %>
<% else %>
<% if current_user.id == (1) %>
<% if current_page? movie_url(@movie.id) %>
        <ul style="float:left;" >


           <% if @movie.picture_file_name.blank? %>
             <li><%= facebox_link_to "Upload picture", :url => new_movie_picture_url %></li>

           <% else %>
             <li><%= button_to "Destroy picture", { :controller=>'movies', :action=>'destroy_picture' }, :confirm => "Are you sure?" %></li>
           <% end %>
           <li><%= facebox_link_to "Edit movie", :url => edit_movie_url %></li>
       </ul>
<% end %>
<% end %>
<% if current_user.id == (2) %>
<% if current_page? movie_url(@movie.id) %>
        <ul style="float:left;" >


           <% if @movie.picture_file_name.blank? %>
             <li><%= facebox_link_to "Upload picture", :url => new_picture_url %></li>

           <% else %>
             <li><%= button_to "Destroy picture", { :controller=>'movies', :action=>'destroy_picture' }, :confirm => "Are you sure?" %></li>
           <% end %>
           <li><%= facebox_link_to "Edit movie", :url => edit_movie_url %></li>
       </ul>
<% end %>
<% end %>
<% end %>
<% end %>

<%= javascript_include_tag 'swfobject', 'jquery.tool' -%>
<%= stylesheet_link_tag 'appleplayer','appleplaylist','player' -%>
<script type="text/javascript">
    var flashvars = { }; 
    var params = { config: "{'clip' : {'url': '<%= @movie.flv.url %>','autoPlay' : false, 'key' : '#$3bc2d7541db86753618'}}"  };
    var so = {};
    so.wmode = "transparent";
    var attributes = { allowFullScreen: true, autoBuffering: true, wmode: "transparent"};       
 swfobject.embedSWF("/swf/flowplayer.commercial-3.1.5.swf", "player", "300", "220", "9.0.0", flashvars, params, so, attributes);

</script>
<script>	

// custom easing called "custom"
$.easing.custom = function (x, t, b, c, d) {
	var s = 1.70158; 
	if ((t/=d/2) < 1) return c/2*(t*t*(((s*=(1.525))+1)*t - s)) + b;
	return c/2*((t-=2)*t*(((s*=(1.525))+1)*t + s) + 2) + b;
}



// use the custom easing
$("div.scrollable").scrollable({easing: 'custom', speed: 700, circular: true});
</script>

app/views/movies/show.iphone.erb
<% content_for :head do %>
  <style type="text/css">
          #header{height:445px !important;} 
          #header_inner{height:420px !important;width:780px;} 
  </style>
<% end %>
<% content_for :hd_inner do %>
 <div class="clear">&nbsp;</div> 
<div id="player_wrap">

	<!-- player container and a nested <h3 style="width:780px;text-align:center;">play button as PNG image -->
	<a id="player" href="">
	 You need to have <%= link_to 'Flash Player','http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash' %> installed to display this video.
	</a>

</div>
<h3 style="width:780px;font:size:14px;text-align:center;padding-bottom:10px;"><%= simple_format h(@movie.name)%></h3>
<% end %>


<div id="clips" class="scrollable">
  <div class="items">
<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (1) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (2) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (3) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (4) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (5) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (6) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>

<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (7) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (8) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (9) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (10) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (11) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (12) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>

<ul class="thumb1">
   <% @movies.each do |movie| %>
     <% if movie.position == (13) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (14) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (15) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (16) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (17) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
     <% if movie.position == (18) %>
      <li><%= link_to image_tag(movie.picture.url, :size => '150x150'), movie_url(movie.id), :title => movie.name %></li>
     <% end %>
   <% end %>
</ul>

</div>
</div>

<a class="next browse right"></a>
<a class="prev browse left"></a>


<h4 style="width:780px;padding-top:10px;font-size:14px !important;text-align:center;">Description</h4>
<div style="width:510px;margin:0 auto;padding:10px;">
            <span><%= simple_format h(@movie.description)%></span>
</div>

<%= javascript_include_tag 'swfobject', 'jquery.tool' -%>
<%= stylesheet_link_tag 'appleplayer','appleplaylist','player' -%>
<script type="text/javascript">
    var flashvars = { }; 
    var params = { config: "{'clip' : {'url': '<%= @movie.flv.url %>','autoPlay' : false, 'key' : '#$3bc2d7541db86753618'}}"  };
    var so = {};
    so.wmode = "transparent";
    var attributes = { allowFullScreen: true, autoBuffering: true, wmode: "transparent"};       
 swfobject.embedSWF("/swf/flowplayer.commercial-3.1.5.swf", "player", "300", "220", "9.0.0", flashvars, params, so, attributes);

</script>
<script>	

// custom easing called "custom"
$.easing.custom = function (x, t, b, c, d) {
	var s = 1.70158; 
	if ((t/=d/2) < 1) return c/2*(t*t*(((s*=(1.525))+1)*t - s)) + b;
	return c/2*((t-=2)*t*(((s*=(1.525))+1)*t + s) + 2) + b;
}



// use the custom easing
$("div.scrollable").scrollable({easing: 'custom', speed: 700, circular: true});
</script>