config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #root "posts#index"
    #root "posts#index"
    
#Ankh::Application.routes.draw do

  get    '/login'                       =>               'user_sessions#new',                         :as => :login
  post   '/create_session'              =>               'user_sessions#create',                      :as => :create_session
  delete '/destroy_session'             =>               'user_sessions#destroy',                     :as => :destroy_session
  
  
#  map.resources :users, :collection => {:prioritize_tasks => :post}
   resources :posts 

#POSTS
  get    '/post/:id'                    =>               'posts#show',                                 :as => :show_post
  post   '/create/post'                 =>               'posts#create',                               :as => :create_post
  get    '/blogger'                     =>               'posts#blogger',                              :as => :blog
  get    '/posts/:id/blogpost'          =>               'posts#edit',                                 :as => :edit_blog
  patch  '/posts/:id/blogupd'           =>               'posts#update',                               :as => :update_blog
  get    '/posts/all/Visible'           =>               'posts#state',                                :as => :visible
  get    '/posts/all/Restricted'        =>               'posts#restricted',                           :as => :restricted
  get    '/fr/posts/all/Visible'        =>               'posts#visiblefr',                            :as => :visiblefr
  get    '/all/textos/Visible'          =>               'posts#textos',                               :as => :model_textos
  get    '/all/links/Visible'           =>               'posts#links',                                :as => :model_links
  get    '/all/images/Visible'          =>               'posts#images',                               :as => :model_images
  get    '/all/videos/mobileVisible'    =>               'posts#videos',                               :as => :model_videos
  delete '/posts/destroy/:post_id'      =>               'posts#destroy',                              :as => :post_destroy
 
#SEARCHS
  get  '/directory/video/:letter'       =>               'searchs#letter_videos',                      :as => :directory_video
  get  '/directory/image/:letter'       =>               'searchs#letter_images',                      :as => :directory_image
  get  '/directory/link/:letter'        =>               'searchs#letter_links',                       :as => :directory_link
  get  '/directory/texto/:letter'       =>               'searchs#letter_textos',                      :as => :directory_texto
  get  '/blog/textos'                   =>               'searchs#textos',                             :as => :adv_model_textos
  get  '/blog/links'                    =>               'searchs#links',                              :as => :adv_model_links
  get  '/blog/images'                   =>               'searchs#images',                             :as => :adv_model_images
  get  '/blog/videos'                   =>               'searchs#videos',                             :as => :adv_model_videos
  get  '/tag_cloud'                     =>               'searchs#tag_cloud',                          :as => :tag_cloud
  get  '/posts/results/date/:date'      =>               'searchs#post_date',                          :as => :post_date

  post  '/search/posts'                 =>               'searchs#research',                           :as => :search
  post  '/search/posts/texts'           =>               'searchs#research_text',                      :as => :search_text
  post  '/search/posts/links'           =>               'searchs#research_link',                      :as => :search_link
  post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  post  '/search/posts/videos'          =>               'searchs#research_video',                     :as => :search_video
  #post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  get   '/directory/posts'              =>               'searchs#index',                              :as => :directory_posts_all

  get  '/directory/posts/:letter'       =>               'searchs#letter',                             :as => :directory_posts_letter
  get  '/posts/tagged/:search'          =>               'searchs#search',                             :as => :posts_tagged_with

#  map.resources :links
#  map.resources :videos
#  map.resources :textos  
  
 # map.resources :users, :collection => {:prioritize_tasks => :post}

#CONTENT
  get    '/content/edit/:id'            =>               'contents#edit',                             :as => :edit_content
  patch  '/content/update/:id'          =>               'contents#update',                           :as => :update_content

#DASHBOARD
  get    '/dashboard'                   =>               'dashboard#show',                            :as => :dashboard
  #post   '/photo/get_new'               =>               'dashboard#get_new_photo',                   :as => :get_new_photo
  get    '/photo/new'                   =>               'dashboard#new_photo',                       :as => :new_photo
  post   '/photo/create'                =>               'dashboard#create_photo',                    :as => :create_photo
  delete '/photo/destroy'               =>               'dashboard#destroy_photo',                   :as => :destroy_photo
  get    '/demo/new'                    =>               'dashboard#new_demo',                        :as => :new_demo
  patch  '/demo/create'                 =>               'dashboard#create_demo',                     :as => :create_demo
  delete '/demo/destroy'                =>               'dashboard#destroy_demo',                    :as => :destroy_demo
  get    '/paragraphe/edit'             =>               'dashboard#paragraphe',                      :as => :paragraphe

#MOVIES
  get    '/movies/:id/edit'             =>               'movies#edit',                                :as => :edit_movie
  get    '/positions/movies'            =>               'movies#position',                            :as => :position_movie
  get    '/movies/:id/picture/new'      =>               'movies#new_picture',                         :as => :new_movie_picture
  post   '/movies/:id/picture/create'   =>               'movies#create_picture',                      :as => :picture
  delete '/movies/:id/picture/destroy'  =>               'movies#destroy_picture',                     :as => :remove_picture
  delete '/movies/:id/destroy'          =>               'movies#destroy',                             :as => :destroy_movie
  get    '/movies/:id/:style.:format'   =>               'movies#connect',                             :as => :connect
  get    '/services'                    =>               'movies#index',                               :as => :services
  get    '/fr/ervices'                  =>               'movies#index',                               :as => :servicesfr

#FOLIOS
  get    '/games'                       =>               'folios#index',                               :as => :folios
  get    '/fr/jeux'                     =>               'folios#index',                               :as => :frfolios
  get    'games/new'                    =>               'folios#new',                                 :as => :new_folio         
  get    '/games/:id/edit'              =>               'folios#edit',                                :as => :edit_folio
  get    '/positions/games'             =>               'folios#position',                            :as => :position_folio
  get    '/games/:id/picture/new'       =>               'folios#new_picture',                         :as => :new_position_folio
  post   '/games/create'                =>               'folios#create',                              :as => :create_folio
  post   '/games/picture/create'        =>               'folios#create_picture',                      :as => :create_folio_picture
  post   '/folios/prioritize_tasks'     =>               'folios#prioritize_tasks',                    :as => :folio_prioritize_tasks
  delete '/games/:id/picture/destroy'   =>               'folios#destroy_picture',                     :as => :remove_folio_picture
  delete '/games/destroy/:id'           =>               'folios#destroy',                             :as => :destroy_folio

 #keep below because of the destroy priority!
  resources :movies, :collection => {:prioritize_tasks => :post}
  resources :folios, :collection => {:prioritize_tasks => :post}
  resources :search, :collection => {:search => :get}
  
  resources :users

# map.connect '/movies/:id/:style.:format', :controller => :movies, :action => :download
#USERS
  get    '/user/:id'                    =>               'users#show',                                     :as => :show_user
  get    '/positions/users'             =>               'users#position',                                 :as => :position
  get    '/aboutus'                     =>               'users#index',                                    :as => :aboutus
  get    '/fr/apropos'                  =>               'users#index',                                    :as => :aboutusfr
  get    '/signup'                      =>               'users#new',                                      :as => :signup

app/views/shared/_business.html.haml
#businesslist.business{:style => "display:none;"}
   %div= link_to 'management', "javascript:fillCookie('busi','busi1', '30');"
   %div= link_to 'mail', "javascript:fillCookie('busi','busi2', '30');" 
   %div= link_to 'advertising', "javascript:fillCookie('busi','busi3', '30');"
   %div= link_to 'billing', "javascript:fillCookie('busi','busi4', '30');" 
   %div= link_to 'languages', "javascript:fillCookie('busi','busi5', '30');" 

app/views/shared/_footer.html.haml
- if current_page?(dashboard_url)
  %ul{:style => "float:left;"}        
    %li= link_to 'Edit profile', "/account/edit", :rel => "shadowbox;width=400;height=700;", :alt => "Edit Profile", :title => ""
    %li= link_to 'Add content', '/paragraphe/edit' 
    - if current_user.id == (1) 
      %li= link_to "Upload movies", new_movie_url 
      %li= link_to "Add employees", signup_url 
      %li= link_to 'Add folio', new_folio_url 
      %li= link_to 'Folio position', position_folio_url
      
    - elsif current_user.id == (2)
      %li= link_to "Upload movies", new_movie_path
      %li= link_to 'Add employees', signup_path 
      %li= link_to 'Add folio', new_folio_path
      %li= link_to 'Folio position', position_folio_path

- elsif current_page?(visible_path) || current_page?(visiblefr_path)
  - unless current_user.nil?  
    %ul{:style => "float:left;"}
      - if current_user.id == (1) 
        %li= link_to 'Manage Posts', posts_path
      - elsif current_user.id == (2)
        %li= link_to 'Manage Posts', posts_path

- elsif current_page?(services_path) || current_page?(servicesfr_path)
  - unless current_user.nil?
    %ul{:style => "float:left;"}
      - if current_user.id == (1)
        %li= link_to 'Set positions', position_movie_path 
      - elsif current_user.id == (2)
        %li= link_to 'Set positions', position_movie_path


- elsif current_page?(aboutus_path) || current_page?(aboutusfr_path)
  - unless current_user.nil?
    %ul{:style => "float:left;"}
      - if current_user.id == (1) 
        %li= link_to 'Set positions', position_path
      - elsif current_user.id == (2) 
        %li= link_to 'Set positions', position_path

- elsif current_page?(posts_path)
  - unless current_user.nil?
    %ul{:style => "float:left;"}
      - if current_user.id == (1)
        %li= link_to 'See restricted', "/posts/all/Restricted" 
      - elsif current_user.id == (2) 
        %li= link_to 'See restricted', "/posts/all/Restricted"
         
%ul{:style => "float:right;"}
  %li
    - if current_user.blank?
      //= facebox_link_to 'Join', :url => signup_url 
      = link_to 'Join', signup_path, :rel => "shadowbox;width=520;height=260;", :alt => "Join", :title => ""
    - else
      = link_to(current_user.login,dashboard_url)
  %li
    - if current_user.blank? 
      //= facebox_link_to 'Login', :url => login_url
      = link_to 'Login', login_path, :rel => "shadowbox;width=520;height=260;", :alt => "Login", :title => ""
    - else 
      = link_to('Logout', destroy_session_url, :confirm => 'Are you sure you want to logout?', :method => :delete) 

.clear &nbsp;
#footer_link
  = link_to image_tag('tools_icn.png', onmouseover: "this.src=\"#{ asset_path 'tools_icon1.png'}\"", onmouseout: "this.src=\"#{ asset_path 'tools_icn.png'}\""), tools_path, :alt => "tool", :title => "tool"
  = link_to image_tag('storage_icn.png', :onmouseover => "this.src=\"#{ asset_path 'storage_icon1.png'}\"", :onmouseout => "this.src=\"#{ asset_path 'storage_icn.png'}\""), hosting_path, :alt => "hosting", :title => "hosting"
  = link_to image_tag('mobile_icn.png', :onmouseover => "this.src=\"#{ asset_path 'mobile_icon1.png'}\"", :onmouseout => "this.src=\"#{ asset_path 'mobile_icn.png'}\""), mobile_path, :alt => "mobile", :title => "mobile" 
  = link_to image_tag('seo_icn.png', :onmouseover => "this.src=\"#{ asset_path 'seo_icon1.png'}\"", :onmouseout => "this.src=\"#{ asset_path 'seo_icn.png'}\""), seo_path, :alt => "seo", :title => "seo" 
  = link_to image_tag('commerce.png', :onmouseover => "this.src=\"#{ asset_path 'ecommerce1.png'}\"", :onmouseout => "this.src=\"#{ asset_path 'commerce.png'}\""), business_path, :alt => "e-commerce", :title => "e-commerce"

app/views/shared/_header.html.erb
  <div id="window">
	<object id="world_foot" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="866" height="220">
		<param name="movie" value="/images/legrenierdemamere.swf">
		<param name="quality" value="high">
		<param name="bgcolor" value="#FFFFFF">
		<param name="wmode" value="transparent">
    	<embed name="world" src="/images/legrenierdemamere.swf" width="866" height="220" quality="high" bgcolor="#FFFFFF" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">
	</object>						
     </div> 
  

app/views/shared/_navfr.html.haml
//#world
//  %object{'classid' => "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000", 'codebase' => "http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0", 'width' => "253", 'height' => "173", 'id' => "earth", 'align' => "middle"}
//    %param{'name' => "allowScriptAccess", 'value' => "sameDomain"}
//    %param{'name' =>"allowFullScreen", 'value' => "false"}
//    %param{'name' => "movie", 'value' => "/assets/earth.swf"}
//    %param{'name' => "quality", 'value' => "high"}
//    %param{'name' => "wmode", 'value' => "transparent"}
//    %param{'name' => "bgcolor", 'value' => "transparent"}     
//    %embed{'src' => "/assets/earth.swf", 'quality' => "high", 'bgcolor' => "transparent", 'wmode' => "transparent", 'width' => "253", 'height' => "173", 'name' => "earth", 'align' => "middle", 'allowScriptAccess' => "sameDomain", 'allowFullScreen' => "false", 'type' => "application/x-shockwave-flash", 'pluginspage' => "http://www.adobe.com/go/getflashplayer"}
#world
  %img#earth{:width => "60px", :height => "60px", :src => "#{ asset_path  'earth1.gif'}", :alt => "The world"}
  //%img#earth_top{:src => "/assets/earth_top1.gif", :alt => "The world"}

%a{:href => "/fr/accueil", :alt => "accueil", :title => "accueil"}
  #link_homepage
= link_to image_tag('logo.jpg'), accueil_path, :class => 'logo', :alt => 'For a new kind of hype', :title => 'Acceuil'
.navi
  %div
    = link_to 'Blog', visiblefr_path
  #services
    %a{:href => "javascript:;", :onClick => "P7_autoLayers(0,'serviceslist')"} Services
  %div
    = link_to 'Réalisations', realisation_fr_path
  %div
    = link_to 'Biographie', aboutusfr_path 
  %div
    = link_to 'Contact', notifierfr_path
  
  = render 'shared/servicesfr'
     

app/views/shared/_portfolio.html.erb
<div id="portfoliolist" class="portfolio" style="display:none;">
  <div><%= link_to 'layouts', '/folios' %></div>
  <div><%= link_to '3D models', '/services' %></div>
  <div><%= link_to 'animations', '/services' %></div>
  <div><%= link_to 'environments', '/environment/nasa' %></div>
</div>

app/views/shared/_portfoliofr.html.erb
<div id="portfoliolist" class="portfolio" style="display:none;">
  <div><%= link_to 'platforme web', '/fr/folios' %></div>
  <div><%= link_to 'modeles 3D', '/fr/services' %></div>
  <div><%= link_to 'animations', '/fr/services' %></div>
  <div><%= link_to 'environements', '/fr/environment/nasa' %></div>
</div>

app/views/shared/_position_folio.html.erb
<div id="position_content">
        <ul id="graphic"class="graphic left">

           <% folios.each do |folio| %>
             <%= render :partial => '/folios/folio', :object => folio %>
             <%#= link_to 'edit', edit_folio_path(folio.id) %>
           <% end %>

        </ul>

</div>

app/views/shared/_position_user.html.erb
<div id="position_content">
        <ul id="graphic<%= current_user.id %>" class="graphic left">

           <% user.each do |user| %>
             <%= render :partial => '/users/user', :object => user %>
           <% end %>

        </ul>

</div>

<% content_for :js do %>
  <% javascript_tag do %>
    $('#graphic<%= current_user.id %>').sortable(
        {
          handle: '.handler',
          items: 'li',
          opacity: 0.4,
          scroll: true,
          update: function(){
            $.ajax({
                type: 'post',
                data: $('#graphic<%= current_user.id %>').sortable('serialize'),
                dataType: 'script',
                complete: function(request){ /*$('#graphic').effect('highlight');*/
                  },
                url: '/users/prioritize_tasks'})
            }
          })
  <% end %>
<% end %>

app/views/shared/_post.html.erb
<% if post.tag_type == 'Visible' %>
  <div class="post_full">
    <%= image_tag 'bubble.jpg', :class => 'tag' -%>
    <% unless post.url.blank? || post.url == 'http://'%>
      <h3><%= link_to truncate(post.url,:lenght => "40",:omission => "..."),  post.url, :popup => 'true', :rel => 'nofollow' %></h3>
    <% end %>
    <h3><%= raw("<span>#{post.title}</span>") unless post.title.blank? %></h3>
    <% unless post.photo.blank? %>
       <div class="post_photo">
         <%= link_to image_tag(post.photo, :size => '55x55', :style => "border:1px solid #ddd;padding:2px;"), post.photo, :popup => true, :rel => 'nofollow' %>
       </div>
    <% end %>
    <div class="clear">&nbsp;</div>
    <div class="blog_body">
    <%= auto_link(simple_format(post.body), :href_options => { :target => "_new"},:rel => "nofollow") %>
    </div>
    <div class="clear">&nbsp;</div>

    <div class="user_box_bg">
      <div class="user_icon">
         <% if current_user && current_user.id == (1) %>
           <%= link_to (image_tag 'comdel.png', :mouseover => 'comdel1.png'), "/posts/destroy/#{post.id}" %>
           <%= facebox_link_to "Edit post", :url => edit_blog_url(post.id) %>
         <% end %>
         <% if current_user && current_user.id == (2) %>
           <%= link_to (image_tag 'comdel.png', :mouseover => 'comdel1.png'), "/posts/destroy/#{post.id}" %>
           <%= facebox_link_to "Edit post", :url => edit_blog_url(post.id) %>
         <% end %>
         <div class="icn_<%= post.model %>"></div>
         <div class="blog_icon">
           <span>posted&nbsp;</span><span style="font-weight:bold;"><%= time_ago_in_words(post.created_at) %></span><span>&nbsp;ago</span>
         </div>
      </div>
   </div>
   
<div class="blog_tag">
         <%= render :partial => 'posts/tag', :collection =>  post.tags %>
      </div>
  <%= image_tag 'gr_post_top.jpg', :class => 'gr_post_top' %>
       <%= image_tag post.user.photo.url(:thumb), :size => '75x75', :style => "border:1px solid #ddd;padding:2px;", :class => 'user_post' %>
   </div>
<div class="clear">&nbsp;</div>
<div class="clear">&nbsp;</div>
<div class="clear">&nbsp;</div>
<% end %>

app/views/shared/_seo.html.erb
<div id="seolist" class="seo" style="display:none;">
   <div><%= link_to 'basic', "javascript:tapeCookie('seo','seo1', '30');" %></div>
   <div><%= link_to 'standard', "javascript:tapeCookie('seo','seo2', '30');" %></div>
   <div><%= link_to 'premium', "javascript:tapeCookie('seo','seo3', '30');" %></div>
</div>

app/views/shared/_seofr.html.haml
#seolist.seo{:style => "display:none;"}
  %div= link_to 'basic', "javascript:tapefrCookie('seo','seo1', '30');"
  %div= link_to 'standard', "javascript:tapefrCookie('seo','seo2', '30');" 
  %div= link_to 'premium', "javascript:tapefrCookie('seo','seo3', '30');" 

app/views/shared/_tab.html.erb
<% if current_page?('/posts/all/Visible') || current_page?('/all/videos/Visible') || current_page?('/post/all/Visible') || current_page?('/all/images/Visible') || current_page?('/all/links/Visible') || current_page?('/all/textos/Visible') %>
  <div class="profile_tab">
    <%#= link_to 'Advanced Mode', '/directory/posts', :style => "width:135px;text-align:center;" %>
  </div>
<% end %>

<% if current_page?('/fr/posts/all/Visible') %>
  <div class="profile_tab">
    <%#= link_to 'Mode Avancé', '/directory/posts', :style =>"width:135px;text-align:center;" %>
  </div>
<% end %>

app/views/shared/_website.html.erb
<div id="websitelist" class="website" style="display:none;">
  <div><%= link_to 'gamers', '/folios' %></div>
  <div><%= link_to 'socials', '/folios' %></div>
  <div><%= link_to 'personnal', '/folios' %></div>
  <div><%= link_to 'business', '/folios' %></div>
</div>

app/views/shared/_websitefr.html.erb
<div id="websitelist" class="website" style="display:none;">
  <div><%= link_to 'gamers', '/fr/folios' %></div>
  <div><%= link_to 'socials', '/fr/folios' %></div>
  <div><%= link_to 'personnal', '/fr/folios' %></div>
  <div><%= link_to 'business', '/fr/folios' %></div>
</div>