config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  #root "posts#index"
    #root "posts#index"
    
#Ankh::Application.routes.draw do

  get    '/login'                       =>               'user_sessions#new',                         :as => :login
  post   '/create_session'              =>               'user_sessions#create',                      :as => :create_session
  delete '/destroy_session'             =>               'user_sessions#destroy',                     :as => :destroy_session
  
  
#  map.resources :users, :collection => {:prioritize_tasks => :post}
   resources :posts 

#POSTS
  get    '/post/:id'                    =>               'posts#show',                                 :as => :show_post
  post   '/create/post'                 =>               'posts#create',                               :as => :create_post
  get    '/blogger'                     =>               'posts#blogger',                              :as => :blog
  get    '/posts/:id/blogpost'          =>               'posts#edit',                                 :as => :edit_blog
  patch  '/posts/:id/blogupd'           =>               'posts#update',                               :as => :update_blog
  get    '/posts/all/Visible'           =>               'posts#state',                                :as => :visible
  get    '/posts/all/Restricted'        =>               'posts#restricted',                           :as => :restricted
  get    '/fr/posts/all/Visible'        =>               'posts#visiblefr',                            :as => :visiblefr
  get    '/all/textos/Visible'          =>               'posts#textos',                               :as => :model_textos
  get    '/all/links/Visible'           =>               'posts#links',                                :as => :model_links
  get    '/all/images/Visible'          =>               'posts#images',                               :as => :model_images
  get    '/all/videos/mobileVisible'    =>               'posts#videos',                               :as => :model_videos
  delete '/posts/destroy/:post_id'      =>               'posts#destroy',                              :as => :post_destroy
 
#SEARCHS
  get  '/directory/video/:letter'       =>               'searchs#letter_videos',                      :as => :directory_video
  get  '/directory/image/:letter'       =>               'searchs#letter_images',                      :as => :directory_image
  get  '/directory/link/:letter'        =>               'searchs#letter_links',                       :as => :directory_link
  get  '/directory/texto/:letter'       =>               'searchs#letter_textos',                      :as => :directory_texto
  get  '/blog/textos'                   =>               'searchs#textos',                             :as => :adv_model_textos
  get  '/blog/links'                    =>               'searchs#links',                              :as => :adv_model_links
  get  '/blog/images'                   =>               'searchs#images',                             :as => :adv_model_images
  get  '/blog/videos'                   =>               'searchs#videos',                             :as => :adv_model_videos
  get  '/tag_cloud'                     =>               'searchs#tag_cloud',                          :as => :tag_cloud
  get  '/posts/results/date/:date'      =>               'searchs#post_date',                          :as => :post_date

  post  '/search/posts'                 =>               'searchs#research',                           :as => :search
  post  '/search/posts/texts'           =>               'searchs#research_text',                      :as => :search_text
  post  '/search/posts/links'           =>               'searchs#research_link',                      :as => :search_link
  post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  post  '/search/posts/videos'          =>               'searchs#research_video',                     :as => :search_video
  #post  '/search/posts/images'          =>               'searchs#research_image',                     :as => :search_image
  get   '/directory/posts'              =>               'searchs#index',                              :as => :directory_posts_all

  get  '/directory/posts/:letter'       =>               'searchs#letter',                             :as => :directory_posts_letter
  get  '/posts/tagged/:search'          =>               'searchs#search',                             :as => :posts_tagged_with

#  map.resources :links
#  map.resources :videos
#  map.resources :textos  
  
 # map.resources :users, :collection => {:prioritize_tasks => :post}

#CONTENT
  get    '/content/edit/:id'            =>               'contents#edit',                             :as => :edit_content
  patch  '/content/update/:id'          =>               'contents#update',                           :as => :update_content

#DASHBOARD
  get    '/dashboard'                   =>               'dashboard#show',                            :as => :dashboard
  #post   '/photo/get_new'               =>               'dashboard#get_new_photo',                   :as => :get_new_photo
  get    '/photo/new'                   =>               'dashboard#new_photo',                       :as => :new_photo
  post   '/photo/create'                =>               'dashboard#create_photo',                    :as => :create_photo
  delete '/photo/destroy'               =>               'dashboard#destroy_photo',                   :as => :destroy_photo
  get    '/demo/new'                    =>               'dashboard#new_demo',                        :as => :new_demo
  patch  '/demo/create'                 =>               'dashboard#create_demo',                     :as => :create_demo
  delete '/demo/destroy'                =>               'dashboard#destroy_demo',                    :as => :destroy_demo
  get    '/paragraphe/edit'             =>               'dashboard#paragraphe',                      :as => :paragraphe

#MOVIES
  get    '/movies/:id/edit'             =>               'movies#edit',                                :as => :edit_movie
  get    '/positions/movies'            =>               'movies#position',                            :as => :position_movie
  get    '/movies/:id/picture/new'      =>               'movies#new_picture',                         :as => :new_movie_picture
  post   '/movies/:id/picture/create'   =>               'movies#create_picture',                      :as => :picture
  delete '/movies/:id/picture/destroy'  =>               'movies#destroy_picture',                     :as => :remove_picture
  delete '/movies/:id/destroy'          =>               'movies#destroy',                             :as => :destroy_movie
  get    '/movies/:id/:style.:format'   =>               'movies#connect',                             :as => :connect
  get    '/services'                    =>               'movies#index',                               :as => :services
  get    '/fr/ervices'                  =>               'movies#index',                               :as => :servicesfr

#FOLIOS
  get    '/games'                       =>               'folios#index',                               :as => :folios
  get    '/fr/jeux'                     =>               'folios#index',                               :as => :frfolios
  get    'games/new'                    =>               'folios#new',                                 :as => :new_folio         
  get    '/games/:id/edit'              =>               'folios#edit',                                :as => :edit_folio
  get    '/positions/games'             =>               'folios#position',                            :as => :position_folio
  get    '/games/:id/picture/new'       =>               'folios#new_picture',                         :as => :new_position_folio
  post   '/games/create'                =>               'folios#create',                              :as => :create_folio
  post   '/games/picture/create'        =>               'folios#create_picture',                      :as => :create_folio_picture
  post   '/folios/prioritize_tasks'     =>               'folios#prioritize_tasks',                    :as => :folio_prioritize_tasks
  delete '/games/:id/picture/destroy'   =>               'folios#destroy_picture',                     :as => :remove_folio_picture
  delete '/games/destroy/:id'           =>               'folios#destroy',                             :as => :destroy_folio

 #keep below because of the destroy priority!
  resources :movies, :collection => {:prioritize_tasks => :post}
  resources :folios, :collection => {:prioritize_tasks => :post}
  resources :search, :collection => {:search => :get}
  
  resources :users

# map.connect '/movies/:id/:style.:format', :controller => :movies, :action => :download
#USERS
  get    '/user/:id'                    =>               'users#show',                                     :as => :show_user
  get    '/positions/users'             =>               'users#position',                                 :as => :position
  get    '/aboutus'                     =>               'users#index',                                    :as => :aboutus
  get    '/fr/apropos'                  =>               'users#index',                                    :as => :aboutusfr
  get    '/signup'                      =>               'users#new',                                      :as => :signup

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  layout 'search'
  before_action :get_alphabet, :except => []
  before_action :get_tag, :except => [:tag_cloud]
  #before_action :get_calendar
  
  def index
    @posts = Post.all.paginate :page => params[:page], :per_page => Post::PER_PAGE
  end

  def letter
    @posts = Post.starts_with(params[:letter]).paginate :page => params[:page], :per_page => Post::PER_PAGE 
    render 'searchs/show'
  end
 
  def letter_textos
    @posts = Post.by_model('textos').by_tag('visible').starts_with(params[:letter]).paginate :page => params[:page], :per_page => Post::PER_PAGE
    render 'searchs/letter'
  end

  def letter_videos
    @posts = Post.by_model('videos').by_tag('visible').starts_with(params[:letter]).paginate :page => params[:page], :per_page => Post::PER_PAGE
    render 'searchs/letter'
  end

  def letter_links
    @posts = Post.by_model('links').by_tag('visible').starts_with(params[:letter]).paginate :page => params[:page], :per_page => Post::PER_PAGE
    render 'searchs/letter'
  end

  def letter_images
    @posts = Post.by_model('images').by_tag('visible').starts_with(params[:letter]).paginate :page => params[:page], :per_page => Post::PER_PAGE
    render 'searchs/letter'
  end


  def textos
    @posts = Post.by_model('textos').by_tag('visible').paginate :per_page => 5, :page => (params[:page] || 1)
    render 'searchs/index'
  end

  def videos
    @posts = Post.by_model('videos').by_tag('visible').paginate :per_page => 5, :page => (params[:page] || 1)
    render 'searchs/index'
  end

  def links
    @posts = Post.by_model('links').by_tag('visible').paginate :per_page => 5, :page => (params[:page] || 1)
    render 'searchs/index'
  end

  def images
    @posts = Post.by_model('images').by_tag('visible').paginate :per_page => 5, :page => (params[:page] || 1)
    render 'searchs/index'
  end

  def search
   # @posts = Post.tagged_with(params[:search],:on => :tags).paginate(:page => params[:page], :per_page => 5)
    @posts = Post.by_tag('visible').tagged_with(params[:search],:on => :tags).paginate :per_page => 5, :page => (params[:page] || 1)
    render 'searchs/index'
  end

  def research
    @posts = Post.search(params[:research],:on => :posts, :with => {:tag_type => "Visible"}, :star => true, :match_mode => :boolean, :page => params[:page], :per_page => Post::PER_PAGE)
    #@posts = @search.paginate :page => params[:page], :per_page => Post::PER_PAGE
    render 'searchs/show'
  end

  def research_video
    @visible = Post.by_state('Visible')
    @posts = @visible.by_kind('videos').search(params[:research],:on => :posts, :star => true, :match_mode => :boolean, :page => params[:page], :per_page => 25)
    render 'searchs/show'
  end

  def research_image
    @visible = Post.by_state('Visible')
    @posts = @visible.by_kind('images').search(params[:research],:on => :posts, :star => true, :match_mode => :boolean, :page => params[:page], :per_page => 25)
    render 'searchs/show'
  end

  def research_link
    @visible = Post.by_state('Visible')
    @posts = @visible.by_kind('links').search(params[:research],:on => :posts, :star => true, :match_mode => :boolean, :page => params[:page], :per_page => 25)
    render 'searchs/show'
  end

  def research_text
    @visible = Post.by_state('Visible')
    @posts = @visible.by_kind('textos').search(params[:research],:on => :posts, :star => true, :match_mode => :boolean, :page => params[:page], :per_page => 25)
    render 'searchs/show'
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
    @tags = params[:letter] ?
      @tags.letter(params[:letter]) :
    @tags.find(:all)
    render 'searchs/tag_cloud'
  end

  def post_date
    @posts = Post.between((params[:date].to_time.utc + 4.hours), (params[:date].to_time.utc + 20.hours)).paginate :page => params[:page], :per_page => Post::PER_PAGE
    @calendar_page_result = true
    render 'searchs/index'
  end
private 
  def get_tag
    @tags = Post.tag_counts_on(:tags).paginate(:page => params[:page], :per_page => 30)
  end
  def get_alphabet
    @alphabet = ('A'..'Z').to_a + ('0'..'9').to_a
  end
  def get_calendar
    @month = Date.today.month.to_i
    @year = Date.today.year.to_i
    @shown_month = Date.civil(@year, @month)
    @event_strips = Event.event_strips_for_month(@shown_month)
  end
end

app/views/searchs/_hd_inner.html.erb
<% if current_page?(adv_model_videos_url) || current_page?(search_video_url) %>

<div id="search_bar">
            <%= form_tag('/search/posts/videos') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>
<h2 class="type_search">VIDEOS</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

  <div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_videos_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_videos_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_video_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

           </h3>
              <% end %>
  </div>
<% else %>
<% if current_page?(adv_model_images_url) || current_page?(search_image_url) %>

<div id="search_bar">
            <%= form_tag('/search/posts/images') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>

<h2 class="type_search">IMAGES</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

  <div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_images_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_images_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_image_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

          </h3>
              <% end %>
  </div>
<% else %>
<% if current_page?(adv_model_links_url) || current_page?(search_link_url) %>

<div id="search_bar">
           <%= form_tag('/search/posts/links') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>
          </div>
<h2 class="type_search">LINKS</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

  <div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_links_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_links_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_link_url(letter)) do |name|
          raw("<span>#{name}</span>")
      end %>

           </h3>
              <% end %>


         </div>
<% else %>
<% if current_page?(adv_model_textos_url) || current_page?(search_text_url) %>

 <div id="search_bar">
            <%= form_tag('/search/posts/texts') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>
          </div>
<h2 class="type_search">TEXTS</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

<div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_textos_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_textos_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_texto_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

           </h3>
              <% end %>
  </div>
<% else %>

<% if current_page?(directory_posts_all_url) || current_page?(search_url) %>

<div id="search_bar">
           <%= form_tag('/search/posts') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>
<h2 class="type_search">ALL</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

<div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? directory_posts_all_url %><span>All</span>
                <% else %><%= link_to "All", directory_posts_all_url  %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_posts_letter_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

</h3>
              <% end %>

         </div>
<% else %>

<% if current_page?('/tag_cloud') %>

<div id="search_bar">
           <%= form_tag('/search/posts') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>


<div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page?('/tag_cloud') %><span>All</span>
                <% else %><%= link_to "All", '/tag_cloud'  %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, { :letter => letter }) do |name|
           raw("<span>#{name}</span>")
      end %>

</h3>
              <% end %>

         </div>
<% else %>
  <% if @calendar_page_result %>
    <h2 class="type_search">EVENT</h2>
  <% end %>
  <div id="search_bar">
           <%= form_tag('/search/posts') do %>
             <p>
                <%= text_field_tag :research, params[:research], :placeholder => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>

<div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? directory_posts_all_url %><span>All</span>
                <% else %><%= link_to "All", directory_posts_all_url  %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_posts_letter_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

</h3>
              <% end %>

         </div>


<% end %>
<% end %>
<% end %>
<% end %>
<% end %>
<% end %>

app/views/searchs/_letter.html.erb
<% if current_page?(directory_video_url) %>

<div id="search_bar">
            <% form_tag('/search/posts/videos') do %>
             <p>
                <%= text_field_tag :research, params[:research], :value => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>
<h2 class="type_search">VIDEOS</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

  <div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_videos_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_videos_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_video_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

           </h3>
              <% end %>
  </div>
<% else %>
<% if current_page?(directory_image_url) %>

<div id="search_bar">
            <% form_tag('/search/posts/images') do %>
             <p>
                <%= text_field_tag :research, params[:research], :value => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>

<h2 class="type_search">IMAGES</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

  <div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_images_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_images_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_image_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

          </h3>
              <% end %>
  </div>
<% else %>
<% if current_page?(directory_link_url) %>

<div id="search_bar">
           <% form_tag('/search/posts/links') do %>
             <p>
                <%= text_field_tag :research, params[:research], :value => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>
          </div>
<h2 class="type_search">LINKS</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

  <div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_links_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_links_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_link_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

           </h3>
              <% end %>


         </div>
<% else %>
<% if current_page?(directory_texto_url)  %>

 <div id="search_bar">
            <% form_tag('/search/posts/texts') do %>
             <p>
                <%= text_field_tag :research, params[:research], :value => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>
          </div>
<h2 class="type_search">TEXTS</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

<div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? adv_model_textos_url %><span>All</span>
                <% else %><%= link_to "All", adv_model_textos_url %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_texto_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

           </h3>
              <% end %>
  </div>
<% else %>

<% if current_page?(directory_posts_letter_url) %>

<div id="search_bar">
           <% form_tag('/search/posts') do %>
             <p>
                <%= text_field_tag :research, params[:research], :value => "search here", :size => '30', :class => 'left search' %>
                <%= submit_tag "Search", :name => nil, :class => 'search_button' %>
             </p>
           <% end %>

          </div>
<h2 class="type_search">ALL</h2>
<h2 class="type_search1">CATEGORIES SEARCH</h2>

<div class="resultat_alpha" style="padding-left:2px;">
           <h3 class="index"><% if current_page? directory_posts_all_url %><span>All</span>
                <% else %><%= link_to "All", directory_posts_all_url  %><% end %></h3>
              <% @alphabet.each do |letter| %>
                 <h3 class="index">
<%= link_to_unless( params[:letter] && letter == params[:letter] , letter, directory_posts_letter_url(letter)) do |name|
           raw("<span>#{name}</span>")
      end %>

</h3>
              <% end %>

         </div>
<% else %>
<% end %>
<% end %>
<% end %>
<% end %>
<% end %>

app/views/searchs/_tag.html.erb
<li><%= link_to tag.name,posts_tagged_with_url(tag.name), :class => 'post_tag', :title => 'tag'%></li>

app/views/searchs/index.html.erb
<% content_for :sidebar do %>
  <%= render :partial => 'shared/sidebar' %>
<% end %>

<% content_for :hd_inner do %>

<div class="entries_wrapper">
<% if @posts.total_entries == 0 %>
<span style="font-size:14px">&nbsp;No result found</span>
<% else %>
<% if @posts.total_entries == 1 %>
<div class="total_entry"><span style="font-size:14px;font-weight:bold;"><%= @posts.total_entries %></span><span style="font-size:14px">&nbsp;result found</span></div>
<% else %>
<div class="total_entry"><span style="font-size:14px;font-weight:bold;"><%= @posts.total_entries %></span><span style="font-size:14px">&nbsp;results found</span></div>
<% end %>
<% end %>
</div>

<div class="share">
  <%= render :partial => 'shared/share' %>
</div>

<!--<div class="info_blog"></div>-->

<%= image_tag 'redlight1.png', :class => 'redlight' %>

<%= render :partial => 'searchs/hd_inner' %>

<%= image_tag 'carbone.jpg', :style => 'height:104px;width:72px;position:absolute;top:-21px;left:0px;' %>
<%= link_to image_tag('all.png', :mouseover => '/assets/all3.png'), "/directory/posts" , :style => 'height:32px;width:32px;position:absolute;top:0px;left:20px;' %>
<%= link_to image_tag('video32.png', :mouseover => '/assets/video32act1.png'), adv_model_videos_url , :style => 'height:32px;width:32px;position:absolute;top:37px;left:20px;' %>
<%= link_to image_tag('image32.png', :mouseover => '/assets/image32act1.png'), adv_model_images_url , :style => 'height:32px;width:32px;position:absolute;top:74px;left:20px;' %>
<%= link_to image_tag('link32.png', :mouseover => '/assets/link32act1.png'), adv_model_links_url , :style => 'height:32px;width:32px;position:absolute;top:109px;left:20px;' %>
<%= link_to image_tag('text32.png', :mouseover => '/assets/text32act1.png'), adv_model_textos_url , :style => 'height:32px;width:32px;position:absolute;top:143px;left:20px;' %>

<% end %>
<div class="clear">&nbsp;</div>
<% if current_page?('/tag_cloud') %>
<div style="width:500px;">

<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>

 <div class="tag_cloud"><a><%= link_to tag.name,"/links/tagged/#{tag.name}" , :class => css_class %></a></div>
<% end %>
   </div>

<% else %>

<% if @posts.total_entries == 0 %>
<div style="height:500px;"><span style="font-size:70px;color:#222;background:#444;border:1px dotted #FFF;margin:50px 0 50px 0;">&nbsp;No result found&nbsp;</span></div>
<% end %>

  <%= render @posts %>
         <div class="paginate"><%= will_paginate @posts %></div>
<% end %>
<div class="clear">&nbsp;</div>

app/views/searchs/tag_cloud.html.erb
<% content_for :sidebar do %>
<%= render :partial => 'shared/sidebar' %>
<% end %>
<% content_for :head do %>
  <style>
     #header_inner{background: url(/assets/cloud.jpg) repeat-x 5px 7px;}
   </style>
<% end %>

<% content_for :hd_inner do %>
<%= image_tag 'redlight1.png', :class => 'redlight', :style => "z-index:1;" %>
<h2 class="type_search" style="z-index:1;">TAG CLOUD</h2>
<%= render :partial => 'searchs/hd_inner' %>

<%= image_tag 'carbone.jpg', :style => 'height:104px;width:72px;position:absolute;top:-21px;left:0px;' %>
<%= link_to image_tag('all.png', :mouseover => 'all3.png'), "/directory/posts" , :style => 'height:32px;width:32px;position:absolute;top:0px;left:20px;' %>
<%= link_to image_tag('video32.png', :mouseover => 'video32act1.png'), adv_model_videos_url , :style => 'height:32px;width:32px;position:absolute;top:37px;left:20px;' %>
<%= link_to image_tag('image32.png', :mouseover => 'image32act1.png'), adv_model_images_url , :style => 'height:32px;width:32px;position:absolute;top:74px;left:20px;' %>
<%= link_to image_tag('link32.png', :mouseover => 'link32act1.png'), adv_model_images_url , :style => 'height:32px;width:32px;position:absolute;top:109px;left:20px;' %>
<%= link_to image_tag('text32.png', :mouseover => 'text32act1.png'), adv_model_images_url , :style => 'height:32px;width:32px;position:absolute;top:143px;left:20px;' %>

<% end %>
<div class="clear">&nbsp;</div>
<div style="width:500px;">

<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
   
 <div class="tag_cloud"><a><%= link_to tag.name,"/posts/tagged/#{tag.name}" , :class => css_class %></a></div>
<% end %>
   </div>